import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Calendar() {
    return (
        <div>
            <Head>
                <title>Calendar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>

                <main>
                    <h1>
                        Here is where the calendar will go...
                </h1>
                </main>
            </Layout>
        </div>
    )
}
