import Head from 'next/head'
import Layout from '../components/layout'
import { useSession } from "next-auth/react"
import React, { useState, useEffect } from 'react'
import axios from 'axios'
import habit from '../models/habit'

export default function Checklist() {
    const { data: session } = useSession()
    const [habits, setHabits] = useState({})
    const [checkedHabits, setCheckedHabits] = useState({})
    const today = new Date().toISOString().slice(0, 10)
    console.log('today', today)

    const getHabits = async () => {
        try {
            const res = await axios.get(`/api/users/${session.user.id}/habits`)

            setHabits(res.data.habits)
        } catch (error) {
            console.log(error)
        }
    }
    useEffect(() => {
        getHabits()
    }, [session])

    // const addLog = async event => {
    //     try {
    //         // event.preventDefault()
    //         const reqBody = { `${habit._id}` : `${habit.name}`}

    //         const res = await axios.post(`/api/users/${session.user.id}/logs/${today}`, reqBody)

    //     } catch (error) {
    //         console.log(error)
    //     }
    // }

    let usersHabits = []
    if (habits.length > 0) {

        usersHabits = habits.filter(habit => habit.userid === session.user.id)
    }
    if (session) {

        return (
            <>
                <div>
                    <Head>
                        <title>Home</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Layout>


                        <main>
                            <h1>Today's Habits:</h1>

                            {usersHabits ? usersHabits.map((habit) => (
                                <>
                                    <p key={habit._id}>{habit.name}</p>
                                    <input id={habit._id} habitname={habit.name} type='checkbox'></input>
                                </>
                            )) : ''}
                        </main>
                    </Layout>
                </div>


            </>
        )
    }

    return (
        <>
            <div>
                <Head>
                    <title>Home</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>


                    <main>
                        <h1>
                            Here is where today's habits will be displayed...</h1>

                    </main>
                </Layout>
            </div>


        </>
    )
}

