import Head from 'next/head'
import Layout from '../components/layout'
// import { useSession, signIn, signOut } from "next-auth/react"
import Image from 'next/image'

import workout from '../public/habit-images/workout.jpeg'
import journal from '../public/habit-images/journal.jpeg'
import walk from '../public/habit-images/walk.jpeg'
import read from '../public/habit-images/read.jpeg'
import skincare from '../public/habit-images/skincare.jpeg'
import meditate from '../public/habit-images/meditate.jpeg'
import water from '../public/habit-images/water.jpeg'
import { useSession } from 'next-auth/react'

export default function Welcome() {
  const { data: session } = useSession()
  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <main>
          <div className="landing">
            <section className="section-a">
              <div className="cont">
                <div>
                  <h1 className="lighter">Welcome to HabitTracker</h1>
                  <h4 className="lighter">A tool for tracking your daily habits so you can improve your physical and mental well-being.</h4>
                  {session ? <a href="/settings" className="btn">Get Started</a> : <a href="/api/auth/signin" className="btn">Get Started</a>}
                </div>
                <Image src={workout} />
              </div>
            </section>

            <section className="section-b">
              <div className="overlay">
                <div className="section-b-inner">
                  <h3>Consistency is key.</h3>
                  <h2>HabitTracker is designed to track your habits <b>every single day</b> so you can keep yourself accountable.</h2>
                  <p>Work towards your goals and monitor your progress all in one place.</p>
                </div>
              </div>
            </section>

            <section className="section-c">
              <div className="gallery">
                <Image className="gal-img" src={journal} />
                <Image className="gal-img" src={walk} />
                <Image className="gal-img" src={read} />
                <Image className="gal-img" src={skincare} />
                <Image className="gal-img" src={meditate} />
                <Image className="gal-img" src={water} />
              </div>
            </section>
          </div>
        </main>
      </Layout>
    </div>
  )
}
