import Head from 'next/head'
import Nav from '../components/nav'
import Script from 'next/script'
import Image from 'next/image'
import workout from '../public/habit-images/workout.jpeg'
import journal from '../public/habit-images/journal.jpeg'
import walk from '../public/habit-images/walk.jpeg'
import read from '../public/habit-images/read.jpeg'
import skincare from '../public/habit-images/skincare.jpeg'
import meditate from '../public/habit-images/meditate.jpeg'
import water from '../public/habit-images/water.jpeg'
import { useSession } from 'next-auth/react'

export default function Welcome() {
  const { data: session } = useSession()
  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Nav />
      <main className="landing">
        <Script src="https://kit.fontawesome.com/3c5f175f7a.js"></Script>

        <div>
          <section className="section-a">
            <div className="cont">
              <div>
                <h1 className="lighter">Welcome to HabitTracker</h1>
                <h4 className="lighter">A tool for tracking your daily habits so you can improve your physical and mental well-being.</h4>
                {session ? <a href="/settings" className="btn">Get Started</a> : <a href="/api/auth/signin" className="btn">Get Started</a>}
              </div>
              <Image src={workout} />
            </div>
          </section>

          <section className="section-b">
            <div className="overlay">
              <div className="section-b-inner">
                <h3>Consistency is key.</h3>
                <h2>HabitTracker is designed to track your habits <b>every single day</b> so you can keep yourself accountable.</h2>
                <p>Work towards your goals and monitor your progress all in one place.</p>
              </div>
            </div>
          </section>

          <section className="section-c">
            <div className="gallery">
              <Image className="gal-img" src={journal} />
              <Image className="gal-img" src={walk} />
              <Image className="gal-img" src={read} />
              <Image className="gal-img" src={skincare} />
              <Image className="gal-img" src={meditate} />
              <Image className="gal-img" src={water} />
            </div>
          </section>
        </div>
      </main>
      <footer className="section-footer">
        <div className="cont">
          <div className="col">
            <h2>Connect with us.</h2>
            <div className="icons">
              <a href="http://twitter.com">
                <i className="fa-brands fa-twitter fa-2x"></i>
              </a>
              <a href="http://facebook.com">
                <i className="fab fa-facebook fa-2x"></i>
              </a>
              <a href="http://instagram.com">
                <i className="fa-brands fa-instagram fa-2x"></i>
              </a>
            </div>
          </div>
          <div className="col">
            <h2>Need Some Inspo?</h2>
            <a href="https://www.webmd.com/fitness-exercise/ss/twelve-habits-super-healthy-people">Check out this article from WebMD.</a>
            <br />
            <a href="https://www.psychologytoday.com/us/blog/lifes-work/202103/7-simple-habits-protect-your-mental-health">Or this one from Psychology Today.</a>
          </div>

        </div>
      </footer>

    </div>
  )
}
