import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Welcome() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link href="/homepage">
            <a>Home</a>
          </Link>
        </li>
        <li>
          <Link href="/calendar">
            <a>Calendar</a>
          </Link>
        </li>
        <li>
          <Link href="/settings">
            <a>Settings</a>
          </Link>
        </li>
      </ul>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to HabitTracker!
        </h1>
      </main>

      <footer className={styles.footer}>
        <h2>footer</h2>
      </footer>
    </div>
  )
}
