import Head from 'next/head'
import Layout from '../components/layout'
import DeleteModal from '../components/deleteModal'
import { useSession } from "next-auth/react"
import React, { useState, useEffect } from 'react'
import axios from 'axios'

export default function Settings() {
    const { data: session } = useSession()
    const [habits, setHabits] = useState({})
    // For delete modal
    const [habitid, setHabitId] = useState(null);
    const [displayConfirmationModal, setDisplayConfirmationModal] = useState(false);
    const [deleteMessage, setDeleteMessage] = useState(null);
    const [message, setMessage] = useState(null)

    const getHabits = async () => {
        try {
            const res = await axios.get(`/api/users/${session.user.id}/habits`)

            setHabits(res.data.habits)
        } catch (error) {
            console.log(error)
        }
    }
    useEffect(() => {
        getHabits()
    }, [session])

    if (session) {
        const addHabit = async event => {
            try {
                // event.preventDefault()
                const reqBody = { habit: event.target.habit.value, userid: session.user.id }

                const res = await axios.post(`/api/habits`, reqBody)

                getHabits()
            } catch (error) {
                console.log(error)
            }
        }
        // const deleteHabit = async (habitid) => {
        //     try {
        //         await axios.delete(`/api/habits/${habitid}`)

        //         getHabits()
        //     } catch (error) {
        //         console.log(error.message)
        //     }
        // }

        let usersHabits = []
        if (habits.length > 0) {

            usersHabits = habits.filter(habit => habit.userid === session.user.id)
        }


        // Handle the displaying of the modal based on id
        const showDeleteModal = async (habitid) => {
            setHabitId(habitid);

            setDeleteMessage('Are you sure you want to delete the habit and its records?');


            setDisplayConfirmationModal(true);
        };

        // Hide the modal
        const hideConfirmationModal = () => {
            setDisplayConfirmationModal(false);
        };

        // Handle the actual deletion of the item
        const submitDelete = async (habitid) => {
            try {
                await axios.delete(`/api/habits/${habitid}`)
                setMessage('Habit was deleted succcessfully');
                setDisplayConfirmationModal(false);

                getHabits()
            } catch (error) {
                console.log(error.message)
            }
        };
        return (
            <div>
                <Head>
                    <title>Settings</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>

                    <main>
                        <h1>
                            My habits
                    </h1>
                        <ul className='habit-list'>
                            {usersHabits.map((habit) => (
                                <li>
                                    <p id={habit._id} key={habit._id}>{habit.name}</p>
                                    <button id={habit._id} className='btn' onClick={() => showDeleteModal(habit._id)}>Delete</button>
                                </li>
                            ))}
                        </ul>


                        <form onSubmit={addHabit}>
                            <input id='habit' name='habit' type="text" placeholder='add a habit' required />

                            <button type='submit'>add habit</button>
                        </form>


                    </main>
                    <DeleteModal showModal={displayConfirmationModal} confirmModal={submitDelete} hideModal={hideConfirmationModal} habitid={habitid} message={deleteMessage} />


                </Layout>
            </div>
        )
    }
    return (
        <>
            <div>
                <Head>
                    <title>Settings</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>


                    <main>
                        <h1>
                            Here is where settings will be displayed...</h1>

                    </main>
                </Layout>

            </div>


        </>
    )
}
