import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Settings() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Settings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ul>
                <li>
                    <Link href='/'>
                        <a>HabitTracker</a>
                    </Link>
                </li>
                <li>
                    <Link href='/Home'>
                        <a>Home</a>
                    </Link>
                </li>
                <li>
                    <Link href='/calendar'>
                        <a>Calendar</a>
                    </Link>
                </li>
            </ul>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Here is where user's habits will be displayed...
                </h1>
            </main>

            <footer className={styles.footer}>
                <h2>footer</h2>
            </footer>
        </div>
    )
}
