import Head from 'next/head'
import Layout from '../components/layout'
import { useSession } from "next-auth/react"
import React, { useState, useEffect } from 'react'
import axios from 'axios'

export default function Settings() {
    const { data: session } = useSession()
    const [habits, setHabits] = useState({})

    const getHabits = async () => {
        try {
            const res = await axios.get(`/api/users/${session.user.id}/habits`)

            setHabits(res.data.habits)
        } catch (error) {
            console.log(error)
        }
    }
    useEffect(() => {
        getHabits()
    }, [session])

    if (session) {
        const addHabit = async event => {
            try {
                // event.preventDefault()
                const reqBody = { habit: event.target.habit.value, userid: session.user.id }

                const res = await axios.post(`/api/habits`, reqBody)

                getHabits()
            } catch (error) {
                console.log(error)
            }
        }
        const deleteHabit = async (habitid) => {
            try {
                await axios.delete(`/api/habits/${habitid}`)

                getHabits()
            } catch (error) {
                console.log(error.message)
            }
        }

        let usersHabits = []
        if (habits.length > 0) {

            usersHabits = habits.filter(habit => habit.userid === session.user.id)
        }
        return (
            <div>
                <Head>
                    <title>Settings</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>

                    <main>
                        <h1>
                            My habits
                    </h1>
                        <div className='habit-list'>
                            {usersHabits.map((habit) => (
                                <>
                                    <p id={habit._id} key={habit._id}>{habit.name}</p>
                                    <button id={habit._id} className='btn' onClick={() => deleteHabit(habit._id)}>Delete</button>
                                </>
                            ))}
                        </div>


                        <form onSubmit={addHabit}>
                            <input id='habit' name='habit' type="text" placeholder='add a habit' required />

                            <button type='submit'>add habit</button>
                        </form>


                    </main>

                </Layout>
            </div>
        )
    }
    return (
        <>
            <div>
                <Head>
                    <title>Settings</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>


                    <main>
                        <h1>
                            Here is where settings will be displayed...</h1>

                    </main>
                </Layout>
            </div>


        </>
    )
}
